/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace LendingAdapter {
  export type PositionStruct = {
    owner: AddressLike;
    collateral: BigNumberish;
    debt: BigNumberish;
    lastUpdated: BigNumberish;
  };

  export type PositionStructOutput = [
    owner: string,
    collateral: bigint,
    debt: bigint,
    lastUpdated: bigint
  ] & { owner: string; collateral: bigint; debt: bigint; lastUpdated: bigint };
}

export interface LendingAdapterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getPosition"
      | "helper"
      | "owner"
      | "positions"
      | "renounceOwnership"
      | "setHelper"
      | "setPosition"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "HelperUpdated"
      | "OwnershipTransferred"
      | "PositionUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getPosition",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "helper", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "positions",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setHelper",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPosition",
    values: [BytesLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "helper", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "positions", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setHelper", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace HelperUpdatedEvent {
  export type InputTuple = [helper: AddressLike];
  export type OutputTuple = [helper: string];
  export interface OutputObject {
    helper: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PositionUpdatedEvent {
  export type InputTuple = [
    positionId: BytesLike,
    owner: AddressLike,
    collateral: BigNumberish,
    debt: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    positionId: string,
    owner: string,
    collateral: bigint,
    debt: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    positionId: string;
    owner: string;
    collateral: bigint;
    debt: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LendingAdapter extends BaseContract {
  connect(runner?: ContractRunner | null): LendingAdapter;
  waitForDeployment(): Promise<this>;

  interface: LendingAdapterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getPosition: TypedContractMethod<
    [positionId: BytesLike],
    [LendingAdapter.PositionStructOutput],
    "view"
  >;

  helper: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  positions: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, bigint] & {
        owner: string;
        collateral: bigint;
        debt: bigint;
        lastUpdated: bigint;
      }
    ],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setHelper: TypedContractMethod<[_helper: AddressLike], [void], "nonpayable">;

  setPosition: TypedContractMethod<
    [
      positionId: BytesLike,
      positionOwner: AddressLike,
      collateral: BigNumberish,
      debt: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getPosition"
  ): TypedContractMethod<
    [positionId: BytesLike],
    [LendingAdapter.PositionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "helper"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "positions"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, bigint] & {
        owner: string;
        collateral: bigint;
        debt: bigint;
        lastUpdated: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setHelper"
  ): TypedContractMethod<[_helper: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPosition"
  ): TypedContractMethod<
    [
      positionId: BytesLike,
      positionOwner: AddressLike,
      collateral: BigNumberish,
      debt: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "HelperUpdated"
  ): TypedContractEvent<
    HelperUpdatedEvent.InputTuple,
    HelperUpdatedEvent.OutputTuple,
    HelperUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PositionUpdated"
  ): TypedContractEvent<
    PositionUpdatedEvent.InputTuple,
    PositionUpdatedEvent.OutputTuple,
    PositionUpdatedEvent.OutputObject
  >;

  filters: {
    "HelperUpdated(address)": TypedContractEvent<
      HelperUpdatedEvent.InputTuple,
      HelperUpdatedEvent.OutputTuple,
      HelperUpdatedEvent.OutputObject
    >;
    HelperUpdated: TypedContractEvent<
      HelperUpdatedEvent.InputTuple,
      HelperUpdatedEvent.OutputTuple,
      HelperUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PositionUpdated(bytes32,address,uint256,uint256,uint256)": TypedContractEvent<
      PositionUpdatedEvent.InputTuple,
      PositionUpdatedEvent.OutputTuple,
      PositionUpdatedEvent.OutputObject
    >;
    PositionUpdated: TypedContractEvent<
      PositionUpdatedEvent.InputTuple,
      PositionUpdatedEvent.OutputTuple,
      PositionUpdatedEvent.OutputObject
    >;
  };
}
